-- ============================================================
-- Smart Food Rescue & Redistribution System
-- Sample Data for Development
--
-- Passwords (BCrypt hashed — change in production):
--   admin@foodrescue.com    → Admin@123
--   donor@foodrescue.com    → Donor@123
--   ngo@foodrescue.com      → Ngo@12345
--   volunteer@foodrescue.com → Vol@12345
--
-- To generate a new BCrypt hash in Java:
--   new BCryptPasswordEncoder().encode("yourpassword")
-- ============================================================

-- Insert sample users (passwords are BCrypt-hashed)
-- BCrypt of "Admin@123"
INSERT INTO users (email, password, full_name, phone, role, enabled, blocked)
SELECT 'admin@foodrescue.com',
       '$2a$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2uheWG/igi.',
       'System Admin', '9000000001', 'ADMIN', true, false
WHERE NOT EXISTS (SELECT 1 FROM users WHERE email = 'admin@foodrescue.com');

-- BCrypt of "Donor@123"
INSERT INTO users (email, password, full_name, phone, role, enabled, blocked)
SELECT 'donor@foodrescue.com',
       '$2a$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2uheWG/igi.',
       'Fresh Bites Restaurant', '9000000002', 'DONOR', true, false
WHERE NOT EXISTS (SELECT 1 FROM users WHERE email = 'donor@foodrescue.com');

-- BCrypt of "Ngo@12345"
INSERT INTO users (email, password, full_name, phone, role, enabled, blocked)
SELECT 'ngo@foodrescue.com',
       '$2a$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2uheWG/igi.',
       'Hope Foundation NGO', '9000000003', 'NGO', true, false
WHERE NOT EXISTS (SELECT 1 FROM users WHERE email = 'ngo@foodrescue.com');

-- BCrypt of "Vol@12345"
INSERT INTO users (email, password, full_name, phone, role, enabled, blocked)
SELECT 'volunteer@foodrescue.com',
       '$2a$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2uheWG/igi.',
       'Raj Kumar (Volunteer)', '9000000004', 'VOLUNTEER', true, false
WHERE NOT EXISTS (SELECT 1 FROM users WHERE email = 'volunteer@foodrescue.com');

-- ============================================================
-- NOTE: The BCrypt hash above is the hash of "password"
-- (from the spring security test password encoder).
-- For development, use the actual BCrypt hashes generated by:
--   BCryptPasswordEncoder().encode("Admin@123") etc.
--
-- IMPORTANT: The application DataInitializer component will
-- create these users with correct hashes on first startup.
-- This SQL is a fallback only.
-- ============================================================
